### PR TITLE
Elk nestedjsoncol

### PR DESCRIPTION
**Pull request by dorirabin**
fix code inside extractFromSource
should fix a problem where a selected columns of the query is mapped to an inner field in the json document (nested) and the value was not extracted

### CODE REVIEW

**Comment by sajjoseph** [comment]
@dorirabin - I noticed that you are referring to the changes as if they are working on [nested](https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html) ES type. But, I believe your code will operate only on "[object](https://www.elastic.co/guide/en/elasticsearch/reference/current/object.html)" type - right? Since this code will work for that particular scenario, we should document the same and add a TODO for true nested datatypes.

**Comment by dorirabin** [comment]
that's true my code handles the case of object datatype (by nested I meant hierarchy but not the nested ES datatype) sorry for the confusion

**Comment by sajjoseph** [comment]
Another interesting issue I came across is this - if a field in ES was marked as "long" type, while retrieve data, Presto might treat the actual data as "Integer" type.

For example, let us use the following column mapping in Presto's table metadata for ES connection:
        {
            "jsonPath": "avgMessageSizeInBytes",
            "jsonType": "long",
            "name": "avgMessageSizeInBytes",
            "ordinalPosition": "2",
            "type": "bigint"
        }

We expect the data to be a BIGINT. If the actual record in ES has a value like 1038 for this field, Presto will receive this data for that record as type INTEGER. And, the current code doesn't handle that. You can check the comment I added for ElasticSearchUtils.java in the original contribution.

**Comment by zhenxiao** [comment]
thank you @dorirabin for the fix
I think you could open a pull request on:
https://github.com/prestodb/presto

I will review there.

Please make sure address @sajjoseph 's comments, at the same time, I'd suggest adding testcases to the code, and make it a single commit.

**Pull request closed without merging**
